<a href="https://colab.research.google.com/github/pranavi2013/AIML_2024/blob/main/lab_1_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
list1=[2,0,1,3]
n1=np.array(list1)
print("list1",list1)
print("n1",n1)
print("type=",type(n1))
print("type=",type(list1))

list1 [2, 0, 1, 3]
n1 [2 0 1 3]
type= <class 'numpy.ndarray'>
type= <class 'list'>


In [ ]:
import numpy as np
arr1=(21,22,23,24)
arr2=(21,22,23,24)
mul=np.multiply(arr1,arr2)
print(mul)
div=np.divide(arr1,arr2)
print(div)
pow=np.power(arr1,arr2)
print(pow)

[441 484 529 576]
[1. 1. 1. 1.]
[-1595931050845505211  4981753131911086080  8450172506621111015
                    0]


In [ ]:
data1 = np.array([3, 5, 7, 9, 11])
data2 =np.array( [3, 4, 5, 6, 7])
print("addition of two array:",data1+data2)

addition of two array: [ 6  9 12 15 18]


In [ ]:
print(np.sin(list1))
print(np.log(list1))
print(np.log2(list1))
print(np.exp(list1))

[0.90929743 0.         0.84147098 0.14112001]
[0.69314718       -inf 0.         1.09861229]
[1.             -inf 0.        1.5849625]
[ 7.3890561   1.          2.71828183 20.08553692]


<ipython-input-6-6fb3c9e0b03b>:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(list1))
<ipython-input-6-6fb3c9e0b03b>:3: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(list1))
